name: EC2 Control

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform: create | stop | terminate"
        required: true
        default: "create"
      input_value:
        description: "Number of instances (create) or Instance IDs (stop/terminate, comma separated)"
        required: false

jobs:
  ec2-control:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Make script executable
        run: chmod +x scripts/manage-ec2.sh

      - name: Run EC2 Management Script
        run: bash scripts/manage-ec2.sh "${{ github.event.inputs.action }}" "${{ github.event.inputs.input_value }}"