name: Stop All EC2

on:
  workflow_dispatch:

jobs:
  stop-ec2:
    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Stop All Running EC2 Instances
        run: |
          INSTANCE_IDS=$(aws ec2 describe-instances \
            --filters Name=instance-state-name,Values=running \
            --query "Reservations[].Instances[].InstanceId" \
            --output text)

          if [ -z "$INSTANCE_IDS" ]; then
            echo "No running instances found"
          else
            echo "Stopping instances: $INSTANCE_IDS"
            aws ec2 stop-instances --instance-ids $INSTANCE_IDS
          fi